### PR TITLE
Find only instance method filter introduced

### PR DESCRIPTION
**Pull request by vishalzanzrukia**
Hi,

You have really done very nice job on reflection api. While using it I have noticed one thing that I am not able to find only instance methods (excluding static). So I have done minor changes which will allow us to find only instance methods from class. Also, I have noticed some code redundancy which corrected.

I hope you don't mind and merge the changes. Please let me know if there is anything.

Regards,
Vishal Z.

### CODE REVIEW

**Comment by gondor** [comment]
@vishalzanzrukia thank you.  I have no problem with contributions and completely welcome them on any of my projects. this looks good overall but have a couple suggestions before I can merge your changes.
1.  How about renaming the StaticType.XXX to MethodType.STATIC || INSTANCE.  I feel it flows better since it relates to the method calls.
2.  Could you delete the commented out code and // TODO's

Thank you and good addition to the library.

**Comment by vishalzanzrukia** [comment]
Hi,

Thanks Jeremy.

Yes, you are absolutely right. I was also not feeling good about
StaticType, but I was not able to think right name.

I will do both the changes and update you.

Thanks again.

Thanks,
Vishal Z.

On 8/22/15, Jeremy Unruh notifications@github.com wrote:

> @vishalzanzrukia thank you.  I have no problem with contributions and
> completely welcome them on any of my projects. this looks good overall but
> have a couple suggestions before I can merge your changes.
> 1.  How about renaming the StaticType.XXX to MethodType.STATIC || INSTANCE.
>    I feel it flows better since it relates to the method calls.
> 2.  Could you delete the commented out code and // TODO's
> 
> Thank you and good addition to the library.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gondor/reflect/pull/1#issuecomment-133648674

## 

_Thanks & Regards_,
_Vishal Zanzrukia_ ( _+91 9727837776 *)
*Software Engineer_ ( _Rishabh Software *)
*Contact me on_ : _Twitter_ https://twitter.com/vishalzanzrukia,
_LinkedIn_
http://www.linkedin.com/profile/view?id=109197299&trk=nav_responsive_tab_profile
, _Google+_ https://plus.google.com/+VishalZanzrukia/about

**Comment by vishalzanzrukia** [comment]
Hi Jeremy,

Can you please check it now? I have done the changes suggested by you. 

Thanks,
Vishal Z.

**Comment by gondor** [comment]
Looks good! Thanks

**Pull request merged**
